// lib/quiz_model.dart

import 'package:hive/hive.dart';

part 'quiz_model.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 1) // New, unique typeId
class SavedQuiz extends HiveObject {
  @HiveField(0)
  final String title;

  @HiveField(1)
  final List<QuizQuestion> questions;

  SavedQuiz({required this.title, required this.questions});
}


@HiveType(typeId: 2) // New, unique typeId
class QuizQuestion extends HiveObject {
  @HiveField(0)
  final String question;

  @HiveField(1)
  final List<String> options;
  
  @HiveField(2)
  final String answer;

  QuizQuestion({required this.question, required this.options, required this.answer});

  // We keep this factory to easily create objects from the AI's JSON response
  factory QuizQuestion.fromJson(Map<String, dynamic> json) {
    return QuizQuestion(
      question: json['question'],
      options: List<String>.from(json['options']),
      answer: json['answer'],
    );
  }
}